name: Build
on:
  push:
    branches:
      - 'dynamic-rewrite'

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # todo(maximsmol): get rid of just
      - name: Set up just
        uses: extractions/setup-just@v1
      - name: Set up buildx
        uses: docker/setup-buildx-action@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Login into Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Compile / Upload
        run: |
          just do-the-thing
      - name: Checkout latch-base
        uses: actions/checkout@v4
        with:
          repository: 'latchbio/latch-base'
          ref: main
          token: ${{ secrets.PAT_TOKEN }}
      - name: DBNP Nextflow
        run:
          just dbnp-nextflow



